CREATE TABLE IF NOT EXISTS bl_dim.dim_dates (
  date_id                   INTEGER PRIMARY KEY,
  full_date                 DATE,
  day_name                  TEXT NOT NULL,
  day_of_week               INTEGER NOT NULL,
  day_of_month              INTEGER NOT NULL,
  day_of_quarter            INTEGER NOT NULL,
  day_of_year               INTEGER NOT NULL,
  week_of_month             INTEGER NOT NULL,
  week_of_year              INTEGER NOT NULL,
  month_actual              INTEGER NOT NULL,
  month_name                TEXT NOT NULL,
  month_name_abbreviated    TEXT NOT NULL,
  quarter_actual            INTEGER NOT NULL,
  quarter_name              TEXT NOT NULL,
  year_actual               INTEGER NOT NULL,
  first_day_of_week         DATE NOT NULL,
  last_day_of_week          DATE NOT NULL,
  first_day_of_month        DATE NOT NULL,
  last_day_of_month         DATE NOT NULL,
  first_day_of_quarter      DATE NOT NULL,
  last_day_of_quarter       DATE NOT NULL,
  first_day_of_year         DATE NOT NULL,
  last_day_of_year          DATE NOT NULL,
  mmyyyy                    TEXT NOT NULL,
  mmddyyyy                  TEXT NOT NULL,
  weekend_indr              TEXT NOT NULL
);