CREATE TABLE IF NOT EXISTS bl_dim.dim_shippers
  (
     shipper_surr_id     		INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
     shipper_id 			    INTEGER NOT NULL,
     name  		    			TEXT NOT NULL,
     start_date					DATE NOT NULL,
     end_date     				DATE NOT NULL,
     is_active					TEXT NOT NULL,
     rating				    	DECIMAL(2, 1) NOT NULL,
     ship_base					DECIMAL(10, 2) NOT NULL,
     ship_rate					DECIMAL(10, 2) NOT NULL,     
     contact_phone				TEXT NOT NULL,
     contact_name				TEXT NOT NULL,     
     current_county				TEXT NOT NULL,
     historic_county            TEXT NOT NULL,
     insert_dt              	TIMESTAMP WITH TIME ZONE NOT NULL,
     update_dt              	TIMESTAMP WITH TIME ZONE NOT NULL
  );